apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-expose-ports
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 32443
  externalIPs:
    - 10.10.10.250
    - 10.111.0.116
    - 10.111.0.200
